[deploy_config]
salt = "a8 demo interop"
chains = ["op_chain_a","op_chain_b"]

[tokenA]
owner_address = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
name = "SuperAncient8"
symbol = "sA8"
decimals = 18

[tokenB]
owner_address = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
name = "SuperUSDC"
symbol = "sUSDC"
decimals = 18
